version: "2"

services:
        web:
                build:
                        context: .
                        args:
                                APP: ''
                                REDIS: 'redis:6379'
                        dockerfile: app
                ports:
                        - "8080:8080"
                links:
                        - redis
                depends_on:
                        - redis
        redis:
                image: redis
                volumes:
                        - '/data:/data'
                        

volumes:
        redis_data:
                external: true



