---
# This playbook contains docker actions that will be run on "remote" host.
- hosts: all
  become: yes 
  tasks:
# sudo apt-get install *
  - name: Install docker packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    tags:
      - docker
 
  # curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - name: Add Docker s official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
      - docker
 
# sudo apt-key fingerprint 0EBFCD88
  - name: Verify that we have the key with the fingerprint
    apt_key:
      id: 0EBFCD88
      state: present
    tags:
      - docker
 
# sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
  - name: Set up the stable repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present
      update_cache: yes
    tags:
      - docker
 
# sudo apt-get update
  - name: Update apt packages
    apt:
      update_cache: yes
    tags:
      - docker
 
# sudo apt-get install docker-ce=18.03.*
  - name: Install docker
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
            - docker-ce
            - docker-ce-cli
            - containerd.io
    notify: Start docker on boot
    tags:
      - docker

  - name: Start docker on boot
    systemd:
      name: docker
      state: started
      enabled: yes

# sudo groupadd docker
  - name: Create "docker" group
    group:
      name: docker
      state: present
    tags:
      - docker
 
# sudo usermod -aG docker ubuntu
  - name: Add remote "ubuntu" user to "docker" group
    user:
      name: ubuntu
      group: docker
      append: yes
    tags:
      - docker
 
# sudo apt-get install docker-compose=1.8.*
  - name: Install docker-compose
    apt:
      name: docker-compose
      state: present
      update_cache: yes
    tags:
      - docker

  - name: Copy file with owner and permissions
    copy:
      src: ./Deployments/
      dest: /home/ubuntu/Deployments

  - name: Create a volume
    docker_volume:
      name: redis_data

  - name: Create and start services
    docker_compose:
      project_src: Deployments
    register: output


